Merge branch `Davi0kProgramsThings:master` into branch `bitfinexcom:v3-beta`.
bitfinexcom/bitfinex-api-py pull request #216
Opened 2023-02-23 20:47 UTC by Davi0kProgramsThings

Release notes to attach to the v3.0.0b1 beta release (and tag):
~~~markdown
## bitfinex-api-py v3.0.0b1 release notes (February 23, 2023)
_Author of these release notes: Davi0k (https://github.com/Davi0k)_

bitfinex-api-py v3-beta launches today with v3.0.0b1!

v3-beta simplify the integration of the Bitfinex API in Python 3.8+ applications.

v3.0.0b1 introduces multiple new features, improvements and bug fixes such as:
* full type-hinting and type-checking support with mypy;
* Lots of bug fixes (including critical bugs) and performance boosts;
* a new websocket client to ensure fast, secure and persistent connections;
* a more user friendly implementation of REST endpoints (with support for 75+ REST endpoints);

A complete CHANGELOG of the changes introduced by v3.0.0b1 will be released soon.

> DISCLAIMER:
Production use of v3.0.0b1 (and all future beta versions) is HIGHLY discouraged.
Beta versions should not be used in applications which require user authentication.
Provide your API-KEY/API-SECRET, and manage your account and funds at your own risk.

### How to install bitfinex-api-py v3.0.0b1

bitfinex-api-py v3.0.0b1 can be installed using pip:
```bash
python3 -m pip install bitfinex-api-py==3.0.0b1
```

### A simple ready-to-run example

<ins>[**More v3-beta examples can be found here.**](https://github.com/bitfinexcom/bitfinex-api-py/tree/v3-beta/examples)</ins>

```python
from bfxapi import Client, PUB_WSS_HOST
from bfxapi.websocket import subscriptions
from bfxapi.websocket.types import TradingPairTicker

# Creates a new client connected to https://api-pub.bitfinex.com/v2.
# API-KEY and API-SECRET have not been provided, so only public resources will be available.
# When the client doesn't need to authenticate users, it's always better to use PUB_REST_HOST and PUB_WSS_HOST.
bfx = Client(WSS_HOST=PUB_WSS_HOST)

# Registers an event listener for the t-ticker-update event.
# t-ticker-update event is emitted when updates on trading pairs tickers are received (e.g. tBTCUSD).
# f-ticker-update event is emitted when updates on funding currencies tickers are received (e.g. fUSD).
@bfx.wss.on("t_ticker_update")
def on_t_ticker_update(subscription: subscriptions.Ticker, data: TradingPairTicker):
    print(f"Data: {data}")

# Registers an event listener for the subscribed event.
# The subscribed event is emitted every time a subscription is accepted by the server.
# <subscription> argument contains all the information about the completed subscription.
@bfx.wss.on("subscribed")
def on_subscribed(subscription: subscriptions.Subscription):
    print(f"Subscription with subId <{subscription['subId']}> has been completed.")

# Registers an event listener for the open event.
# The open event will be emitted when the connection is opened.
# Event listeners can be coroutines if they need to handle asyncio operations.
@bfx.wss.once("open")
async def on_open():
    # Subscribes the client to tBTCUSD's ticker public channel.
    await bfx.wss.subscribe("ticker", symbol="tBTCUSD")

# Starts the websocket client with a single connection (default is 5).
# Each connection can handle up to 25 subscriptions to public channels.
# For example, if you know that your application will subscribe to 175 public channels,
#     you will have to use 175 / 25 = 7 connections to handle all subscriptions.
# The default number of connections is 5; so, if the <connections> argument is not provided,
#     the client will be able to handle a maximum of 25 * 5 = 125 subscriptions.
# Keep in mind that using a large number of connections could slow down the client performance,
#     the use of more than 20 connections is strongly discouraged.
bfx.wss.run(connections=1)
```
~~~

2023-02-24 17:37 UTC, vigan-abd requested changes

2023-02-24 17:37 UTC, vigan-abd commented on bfxapi/enums.py
> +    ERR_READY = 11000
one thing, please configure your IDE to append newline to end of each file as it's linux standard

2023-02-24 17:37 UTC, vigan-abd commented on bfxapi/urls.py
> +STAGING_REST_HOST = "https://api.staging.bitfinex.com/v2"
please remove all staging related urls

2023-02-24 17:37 UTC, vigan-abd commented on bfxapi/utils/logger.py
> +class ColoredLogger(logging.Logger):
do we support also non colored logging, e.g. it's useful when you want to pipe stdout to a file

2023-02-24 17:37 UTC, vigan-abd commented on examples/rest/merchant/submit_invoice.py
> +# python -c "import examples.rest.merchant.submit_invoice"
can we add later support for the rest of merchant endpoints please? it's really useful for 3rd parties
https://docs.bitfinex.com/reference/merchant-endpoints

2023-02-24 17:37 UTC, vigan-abd commented on pylint.rc
> -[MESSAGES CONTROL]
let's add support for pylint, we need to have same syntax across all project

2023-04-05 13:26 UTC, itsdeka approved these changes
LGTM

2023-04-07 07:58 UTC, vigan-abd approved these changes

2023-04-07 08:49 UTC, merged